$schema: 'https://schemas.wp.org/trunk/theme.json'
version: 3
settings:
  appearanceTools: true
  color:
    defaultDuotone: false
    defaultPalette: false
    defaultGradients: false
    palette:
      - color: '#C02C29'
        name: Primary
        slug: primary
      - color: '#e32723'
        name: 'Primary : Focused'
        slug: primary-focused
      - color: '#232323'
        name: Contrast
        slug: contrast
      - color: '#5c5c5c'
        name: 'Contrast : Soft'
        slug: contrast-soft
      - color: '#E5E5E5'
        name: Accent
        slug: accent
      - color: '#FFFFFF'
        name: White
        slug: white
      - color: '#000000'
        name: Black
        slug: black
  layout:
    contentSize: 1110px
    wideSize: 1366px
  spacing:
    defaultSpacingSizes: false
    spacingSizes:
      - name: 'Tiny'
        size: 0.64rem
        slug: 'tiny'
      - name: 'Small'
        size: 'min(1.5rem, 2vw)'
        slug: 'small'
      - name: 'Regular'
        size: 'min(2.5rem, 3vw)'
        slug: 'regular'
      - name: 'Medium'
        size: 'min(4rem, 5vw)'
        slug: 'medium'
      - name: 'Large'
        size: 'min(6.5rem, 8vw)'
        slug: 'large'
      - name: 'Larger'
        size: 'min(10.5rem, 13vw)'
        slug: 'larger'
    units:
      - '%'
      - px
      - em
      - rem
      - vh
      - vw
  typography:
    fluid: true
    defaultFontSizes: false
    fontFamilies:
      - fontFace:
          - fontFamily: Inter
            fontStretch: normal
            fontStyle: normal
            fontWeight: 300 900
            src:
              - 'file:./assets/fonts/inter/Inter-VariableFont_slnt,wght.woff2'
        fontFamily: '"Inter", sans-serif'
        name: Inter
        slug: body
      - fontFace:
          - fontFamily: Montserrat
            fontStretch: normal
            fontStyle: normal
            fontWeight: 300 400 500 600 700 800 900
            src:
              - 'file:./assets/fonts/montserrat/Montserrat-VF.woff2'
        fontFamily: '"Montserrat", sans-serif'
        name: Montserrat
        slug: heading
      - fontFamily: >-
          -apple-system, BlinkMacSystemFont, avenir next, avenir, segoe ui, helvetica neue, helvetica, Cantarell, Ubuntu, roboto, noto, arial,sans-serif
        name: System Sans-serif
        slug: system-sans-serif
      - fontFamily: >-
          Iowan Old Style, Apple Garamond, Baskerville, Times New Roman, Droid
          Serif, Times, Source Serif Pro, serif, Apple Color Emoji, Segoe UI
          Emoji, Segoe UI Symbol
        name: System Serif
        slug: system-serif
    fontSizes:
      - fluid: false
        name: Tiny
        size: 0.79rem
        slug: tiny
      - fluid: false
        name: Small
        size: 0.889rem
        slug: small
      - fluid: false
        name: Normal
        size: 1rem
        slug: normal
      - fluid: false
        name: H6
        size: 1.125rem
        slug: heading-6
      - fluid: false
        name: H5
        size: 1.266rem
        slug: heading-5
      - fluid: false
        name: H4
        size: 1.424rem
        slug: heading-4
      - fluid: false
        name: H3
        size: 1.602rem
        slug: heading-3
      - fluid: false
        name: H2
        size: 1.802rem
        slug: heading-2
      - fluid: false
        name: H1
        size: 2.027rem
        slug: heading-1

      - fluid:
          min: 1.39rem
          max: 1.85rem
        name: Large
        size: 1.85rem
        slug: large
      - fluid:
          min: 1.85rem
          max: 2.5rem
        name: Extra Large
        size: 2.5rem
        slug: x-large
      - fluid:
          min: 2.5rem
          max: 3.27rem
        name: Extra Extra Large
        size: 3.27rem
        slug: xx-large
    writingMode: true
  useRootPaddingAwareAlignments: true
  custom:
    fontWeight:
      black: 900
      extraBold: 800
      bold: 700
      semiBold: 600
      medium: 500
      regular: 400
      light: 300
      extraLight: 200
      thin: 100
    lineHeight:
      initial: 1
      xxSmall: 1.2
      xSmall: 1.3
      small: 1.4
      medium: 1.45
      large: 1.6
    borderRadius:
      xxSmall: 4px
      xSmall: 6px
      small: 8px
      medium: 12px
      large: 16px
      xLarge: 20px
      xxLarge: 24px
      full: 999px
styles:
  blocks:
    core/separator:
      color:
        text: var(--wp--preset--color--contrast)
      css: !include src/theme/elements/core/separator.css
  color:
    background: var(--wp--preset--color--white)
    text: var(--wp--preset--color--contrast)
  typography:
    fontSize: var(--wp--preset--font-size--normal)
    fontFamily: var(--wp--preset--font-family--body)
    fontWeight: var(--wp--custom--font-weight--regular)
    lineHeight: var(--wp--custom--line-height--large)
  elements:
    heading:
      color:
        text: var(--wp--preset--color--contrast)
      typography:
        fontFamily: var(--wp--preset--font-family--heading)
        fontWeight: '600'
        lineHeight: '1.2'
    h1:
      typography:
        fontSize: var(--wp--preset--font-size--heading-1)
        lineHeight: '1.15'
    h2:
      typography:
        fontSize: var(--wp--preset--font-size--heading-2)
    h3:
      typography:
        fontSize: var(--wp--preset--font-size--heading-3)
    h4:
      typography:
        fontSize: var(--wp--preset--font-size--heading-4)
    h5:
      typography:
        fontSize: var(--wp--preset--font-size--heading-5)
    h6:
      typography:
        fontSize: var(--wp--preset--font-size--heading-6)
    link:
      color:
        text: var(--wp--preset--color--primary)
      typography:
        textDecoration: none
      ':hover':
        color:
          text: var(--wp--preset--color--contrast)
        typography:
          textDecoration: underline
      ':focus':
        color:
          text: var(--wp--preset--color--contrast)
        typography:
          textDecoration: underline
templateParts:
  - area: header
    name: header
    title: Header
  - area: footer
    name: footer
    title: Footer
  - area: uncategorized
    name: sidebar
    title: Sidebar
  - area: uncategorized
    name: post-meta
    title: Post Meta
customTemplates:
  - name: page-no-title
    postTypes:
      - page
    title: Page No Title
  - name: page-with-sidebar
    postTypes:
      - page
    title: Page with Sidebar
  - name: page-wide
    postTypes:
      - page
    title: Page with Wide Image
  - name: single-with-sidebar
    postTypes:
      - post
    title: Single with Sidebar
